### ISSUE TITLE
Node IDs Should Be Optional

### ISSUE THREAD

**Issue by ldo** [pycollada/pycollada#100]
Hi. According to both versions 1.4.1 and 1.5 of the Collada spec, the “id” attribute on a &lt;node&gt; is not supposed to be mandatory. I am working around this in my [`bpycollada` fork](https://github.com/ldo/blender_pycollada_importexport) by delving a bit more directly into the XML layer for now.

**Comment by jterrace** [comment]
What happens right now if there's no id? I thought I recall we generate one if it's not present?

**Comment by ldo** [comment]
Traceback (most recent call last):
      File "/home/ldo/.config/blender/2.83/scripts/addons/pycollada_importexport/__init__.py", line 212, in execute
        return export_collada.save(self, context, **kwargs)
      File "/home/ldo/.config/blender/2.83/scripts/addons/pycollada_importexport/export_collada.py", line 801, in save
        exporter.object(o)
      File "/home/ldo/.config/blender/2.83/scripts/addons/pycollada_importexport/export_collada.py", line 627, in object
        node = self.node(b_matrix)
      File "/home/ldo/.config/blender/2.83/scripts/addons/pycollada_importexport/export_collada.py", line 305, in node
        node = Node(id = None)
      File "/usr/lib/python3/dist-packages/collada/scene.py", line 352, in __init__
        self.xmlnode = E.node(id=self.id, name=self.id)
      File "src/lxml/builder.py", line 210, in lxml.builder.ElementMaker.__call__
      File "src/lxml/builder.py", line 197, in lxml.builder.ElementMaker.__init__.add_dict
    KeyError: <class 'NoneType'>

**Comment by abassign** [comment]
Hi, I would like to use FreeCAD together with the pycollada expert module to be able to directly insert the 3D models made with Freecad in Flightgear which uses Open Scene Graph 3.6.5 (OSG)
The OSG version allows you to read collada files directly, this makes it much easier to use FreeCAD with OSG.
The problem I currently observe is that in the <library_visual_scenes> section the tag <node id = "node0" name = "node0"> does not report the name of the FreeCAD object to which the node refers. This is a big problem that makes the practical use of pycollada impossible with OSG as the numbering of the nodes depends on the insertion order in the corresponding FreeCAD file, as soon as I modify the file the order changes and the program in OSG loses the references. I know about the 24 characters max length problem on names, but currently with Blender 2.8 the problem no longer exists. It would be interesting to change the name assignment by inserting a specific option.
Is it possible to make this change?
So I can go on with the OSG project I am following (Flightgear).

**Comment by ogsadmin** [comment]
Hi @abassign - I have a similar issue (see #130) and think this could possibly also solve yours.

If my suggestion from #130 could be implemented, then the FreeCAD collada export function (see https://github.com/FreeCAD/FreeCAD/blob/d5b0dac635da7a5330a588284b8bfd7ad43a4229/src/Mod/Arch/importDAE.py#L321) could also be enhanced to write the model tree names directly into the name field....
