### ISSUE TITLE
No support for creating bones and skin controllers

### ISSUE THREAD

**Issue by Kevinn1109** [pycollada/pycollada#101]
I have been working with this package to be able to take advantage of the Collada system, but so far I have had very though luck constructing a brand new dae file. The tutorial in the documentation covers the basics like geometry, materials and scenes, but other than that there is very little documentation.

One important aspect of Collada that made me use this framework is the skin modifier to assign bones to geometry. This framework does support the skin controller and the properties to make it work, but there is no way as far as I can tell to create a brand new skin and assign it to the mesh. The constructor of Skin makes it seem like it doesn't need any xml input, but in its code it throws an error if it is missing, since there is no check for it. 

Of course I could be wrong, and am taking the wrong approach to construct a skin modifier by calling its constructor directly, but the documentation really makes me think that this is the way and that this is simply not supported yet. Is this really the case?

**Comment by jterrace** [comment]
That's right: the support isn't there. See #16 

You can also try the 1.5 branch, though I don't maintain it: https://github.com/pycollada/pycollada/tree/collada15spec
