### ISSUE TITLE
missing .close() on Collada().__init__() method

### ISSUE THREAD

**Issue by davelajoie** [pycollada/pycollada#108]
unittest is throwing warnings whenever involving pycollada, where open statement should be using "with open()" or call .close() to close the file handle.

```
        if isinstance(filename, basestring):
            fdata = open(filename, 'rb')
            self.filename = filename
            self.getFileData = self._getFileFromDisk
        else:
            fdata = filename # assume it is a file like object
            self.filename = None
            self.getFileData = self._nullGetFile
        strdata = fdata.read()
        fdata.close() <<<<< missing!
```

**Comment by jterrace** [comment]
Can you clarify how you get the warnings to show up? I'm not seeing them.

**Comment by davelajoie** [comment]
whenever I am using unittest, this gets trapped as warning

**Comment by davelajoie** [comment]
suggest to use "with open()" which solves that problem

**Comment by jterrace** [comment]
I don't see it when I run the pycollada unit tests though. Can you tell me more about your unittest setup so I can repro it?

**Comment by davelajoie** [comment]
I will give you a repro steps, hang on

**Comment by davelajoie** [comment]
`python pycol_bugs.py 
pycol_bugs.py:173: ResourceWarning: unclosed file <_io.BufferedReader name='/var/folders/90/2zp9njmn29g3ztv7drth0mzr0000gp/T/34544b79-5fb9-434e-94e8-7dd05f3a8389.dae'>
  validate_output = False            )
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 1 test in 0.004s
[pycol_bugs.py.zip](https://github.com/pycollada/pycollada/files/7530363/pycol_bugs.py.zip)
`

**Comment by davelajoie** [comment]
python 3.7.7 64 bits macosx

**Comment by jterrace** [comment]
Thanks, I can see it using `python tests/test_collada.py` too, but not when running using pytest.
