### ISSUE TITLE
COLLADA mesh size

### ISSUE THREAD

**Issue by AeroDEmi** [pycollada/pycollada#124]
Hi guys,
I have two COLLADA files that I created using blender, they are the same but have different sizes:
<img width="838" alt="Captura de Pantalla 2022-02-08 a la(s) 11 55 02" src="https://user-images.githubusercontent.com/44657733/153047016-7160caee-2257-4bb4-be66-8fb55d56cea8.png">
 
How can I tell the size with pycollada? Is it possible?

The indices, vertex, vertex_index, texcoordset and texcoord_indexset have the same shape and values

**Comment by jterrace** [comment]
So what differs about the files? Is it the instantiation of the mesh in the
scene?

**Comment by AeroDEmi** [comment]
Same subdivisions, only the size for the small one is 1m and the other is 2m:
<img width="279" alt="Captura de Pantalla 2022-02-08 a la(s) 12 40 03" src="https://user-images.githubusercontent.com/44657733/153054023-989796db-8546-4cc6-9473-568212206ee2.png">

**Comment by jterrace** [comment]
I understand that's what it looks like in blender, but size there is not a
collada term. I would suggest taking a look at the XML of the two files,
you could even do a diff of them. I'm guessing the <scene> will look
different between the two files.

**Comment by AeroDEmi** [comment]
Will look into it, thank you

**Comment by AeroDEmi** [comment]
Am I doing this correctly?
![Captura de Pantalla 2022-02-08 a la(s) 17 32 23](https://user-images.githubusercontent.com/44657733/153093460-9b9e16aa-9c59-4b83-beb9-7408f8d08ded.png)
