### ISSUE TITLE
Reading the <skeleton> node

### ISSUE THREAD

**Issue by Crowfunder** [pycollada/pycollada#129]
Is there any elegant way to read the `<skeleton>` node from `library_visual_scenes/visual_scene/node/instance_controller`  other than manually extracting it from instance_controller's xmlnode?

Or, at the very least, is there a way to directly access the node object mentioned in the aforementioned "skeleton" node from the controller's level?

**Comment by jterrace** [comment]
You can access the raw node via the `.xmlnode` properties. But we don't have parsing support for 1.5.

**Comment by jterrace** [comment]
Duplicate of #25
