### ISSUE TITLE
Allow to set the <node> name and id attributes

### ISSUE THREAD

**Issue by ogsadmin** [pycollada/pycollada#130]
The collada specs (V1.4) defines, that the `<node>` element might have two attributes:
- `id` (optional, but if present must be unique)
- `name` (optional, to name the node, duplicate names allowed)

Unfortunately the `collada.scene.Node` class in pycollada only has the `id` property - when writing out the object as XML, it uses the `id` value to write the `id` and `name`  XML attributes:

https://github.com/pycollada/pycollada/blob/c1987ed630b8161049c034406a0b1fc99e1ccd7e/collada/scene.py#L391-L393

Would it be possible to add an additional `name` property to the `collada.scene.Node` class? I guess this could be empty by default (for backwards compatibility) and only be used if set externally.

The use case for this is to keep model node names, especially when converting from another format (I use FreeCAD to convert STEP models into DAE and now loose the STEP model component tree names when converting - FreeCAD has all names in its internal data structure, but has no way to set them when exporting to DAE (it is using pycollada)). 

Thanks!

**Comment by jterrace** [comment]
Yes, I don't think it would be too difficult to add. Pull requests welcome.
