### ISSUE TITLE
Blender collada importer

### ISSUE THREAD

**Issue by blender-girl** [pycollada/pycollada#135]
Hi

the included collada imported in Blender is having some issues:

- missing textures
- missing parts of objects
- 30k or more objects in a model not working

Is there anybody having the knowledge to make a Blender add-on (importer) for collada file using pycollada?

Thank you

**Comment by jterrace** [comment]
There are some blender importers using pycollada:

 - https://github.com/skrat/bpycollada
 - https://github.com/ldo/blender_pycollada_importexport (fork of the one above)

I'm not aware of others, but you'll have to ask maintainers of those projects. If there are concrete bugs in pycollada, feel free to file them here.
