### ISSUE TITLE
Version Number Seems Stuck at 0.4.1

### ISSUE THREAD

**Issue by fishbotics** [pycollada/pycollada#136]
Hi all, 

This is kind of a strange question but when I run:

```
import collada
print(collada.__version__)
```

I seem to always get 0.4.1. I verified by running `pip uninstall pycollada`, verified that I can't import it, and then reinstalled with  `pip install pycollada==0.7.2`. When I open up the terminal and print the version again, I get 0.4.1 again.

**Comment by fishbotics** [comment]
I think the reason is that this version number is hardcoded in the __init__.py file: https://github.com/pycollada/pycollada/blob/master/collada/__init__.py#L21

**Comment by jterrace** [comment]
Thanks, not sure how I missed that.
