### ISSUE TITLE
Polygon with a hole

### ISSUE THREAD

**Issue by EgorPichugin** [pycollada/pycollada#138]
Hey, I have a problem with creating a polygon with a hole via pycollada.

As I have seen from the documentation, it is possible through the collada.polygons.Polygons class. I have tried different methods, but all my attempts have been unsuccessful.

The most obvious approach is to create two polygons and include them in one geometry.

```
polygon_src = source.FloatSource("polygon_vertex", polygon_vertices, ('X', 'Y', 'Z'))
hole_src = source.FloatSource("hole_vertex", hole_vertices, ('X', 'Y', 'Z'))

geom = geometry.Geometry(mesh, "wall", "polygon_hole", [polygon_src, hole_src])

input_list = source.InputList()
input_list.addInput(0, 'VERTEX', "#polygon_vertex")
input_list.addInput(1, 'VERTEX', "#hole_vertex")

polygon = geom.createPolygons(indices_plgn, input_list, 'mymaterial')
hole = geom.createPolygons(indices_hole, input_list, 'mymaterial')

geom.primitives.append(polygon)
geom.primitives.append(hole)

mesh.geometries.append(geom)
```

However, it does not work. I would be grateful if you could provide me with the general principles on how to achieve it.

**Comment by jterrace** [comment]
Hi, there isn't really much to go on here: you didn't include the vertices and you didn't say how exactly it doesn't work. In theory what you're saying there should work.
