### ISSUE TITLE
0.8 no longer exposes collada.DaeUnsupportedError which breaks DAE import in FreeCAD

### ISSUE THREAD

**Issue by Overruler** [pycollada/pycollada#146]
Version 0.8 no longer exposes collada.common.DaeUnsupportedError as collada.DaeUnsupportedError, which is a backwards incompatible change. This breaks DAE import in FreeCAD.

I cannot find any mention of such a change in the Backwards Compatibility Notes section in the [0.8 pycollada documentation Changelog](https://pycollada.readthedocs.io/en/latest/changelog.html#backwards-compatibility-notes). This leads me to believe that this is an unintentional breakage.

**Comment by jterrace** [comment]
It looks like it was removed in https://github.com/pycollada/pycollada/commit/3052d65cb7ca2478980a9254947a33533c4b6fe0#diff-f3b72bfc3c2aa923902de3bbe3e4ca85a5851511cd757e12b10bde6b5e8e377a

But note that this exception class has always been in collada.common:
https://pycollada.readthedocs.io/en/latest/reference/generated/collada.common.DaeUnsupportedError.html

Users really should be importing from where it's defined, not through an indirect import in the main module. I could add it back, but I'd rather not. Is this causing some problems upstream?

**Comment by Overruler** [comment]
It has broken the [main FreeCAD branch](https://forum.freecad.org/viewtopic.php?t=84626), which [has incorporated a change](https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Arch/importDAE.py#L122) to fix it, as well as breaking another FreeCAD fork with a much more comprehensive DAE support which is the one that I'm using, [which has not](https://github.com/realthunder/FreeCAD/blob/LinkStable/src/Mod/Arch/importDAE.py#L211). This is all I know.
