### ISSUE TITLE
pycollada compatible with python-dateutil 2.X?

### ISSUE THREAD

**Issue by hobbes1069** [pycollada/pycollada#43]
May not be an issue at all but wanted to check. The maintainer of python-dateutil is planning an upgrade of the current 1.5 version to current 2.X.

**Comment by jterrace** [comment]
We use 2.x for python 3.x and 1.5 for python 2.x, since python-dateutil > 1.5 is not compatible with python 2.x anymore. Or is that changing?

**Comment by hobbes1069** [comment]
I'd have to check... Fedora has toyed with moving to Python 3 as default but there's still a lot of legacy stuff that is not compatible with 3. I'll dig a bit more, but is it safe to say that pycollada is fine either way? (assuming that the appropriate version of dateutil is used with Python 2/3?)

**Comment by jterrace** [comment]
Yes. If you take a look at the dateutil docs - 1.5 is the last version compatible with 2.x. 2.0 and above are for python 3.x.
