### ISSUE TITLE
[renamed] How do I get image names and XML data?

### ISSUE THREAD

**Issue by Tcll** [pycollada/pycollada#44]
seeing as how this was used with blender and that, I'd thought to integrate this into my program as a library so my exports would work with blender :)

my program passes the files it manages down to it's scripts which read and write the data.
I can build a library interface between a script and this to pass the data between this and back to the script for further analysis.
so would this be able to accept and return an XML string of the file??

    # script header
    ugeScriptType(UGE_MODEL_SCRIPT)
    ugeScriptFormats('Collada', ['dae'])
    ugeScriptLibs(['pycollada'])
    
    
    def ugeImportModel( FileTypes, UI_Results):
        # setdata() as the placeholder for pycollada's XML import method
        setdata( string(0) ) # pass the file from my interface to pycollada
        
        # apply model data from pycollada here
    
    
    def ugeExportModel( FileTypes, UI_Results):
        
        # apply model data to pycollada here
        
        # getdata() as the placeholder for pycollada's XML export method
        string( getdata() ) # pass the XML data from pycollada to my interface and write it to the file

also, I've noticed a request for PIL integration...
can this be skipped to simply return the image name to my script so my program can import the image??

ugeSetImageData('image.png') # reads image.png, passing the data to my interface
ugeGetImageData('image.png') # writes image.png, passing the data from my interface

thanks :)

**Comment by Tcll** [comment]
out the first portion, just like pillow I need StringIO heh

but how do I get the texture image to send to my program??

**Comment by Tcll** [comment]
figured out one thing, I think, from the example src.

    colladaimage = value.sampler.surface.image
    print colladaimage.id

so if I'm right on this:

    ugeSetImageData( colladaimage.id ) # import image to UMC, not pycollada

**Comment by jterrace** [comment]
I don't understand what question you're asking.

Do you just want to get the path to texture images located in the file?

**Comment by Tcll** [comment]
> Do you just want to get the path to texture images located in the file?

yes please :)


and as for the other half of the question.
I need the XML data of the entire document please. :)

**Comment by jterrace** [comment]
Hmm, looks like the docs reference pages are broken. I'll see if I can figure out what's going wrong with readthedocs.

**Comment by Tcll** [comment]
your whelcome :3

and thanks :)

**Comment by jterrace** [comment]
Docs are working again. To get the path to a texture, use the `path` property:
http://pycollada.readthedocs.org/en/latest/reference/generated/collada.material.CImage.html#collada.material.CImage.path

For the XML contents, access the `xmlnode` attribute of the main `Collada` object:
http://pycollada.readthedocs.org/en/latest/reference/generated/collada.Collada.html#collada.Collada.xmlnode
That is of type [ElementTree](https://docs.python.org/2/library/xml.etree.elementtree.html) which you can convert to a string.

**Comment by Tcll** [comment]
thanks :)

**Comment by Tcll** [comment]
just one last verification...

    def ugeExportModel(T,C):
        dae = Collada() # blank object to be filled with data
        
        # set dae data here
        
        string( dae.xmlnode.__str__() ) # write data to file

looks good??

also, docs are borked again :P

**Comment by jterrace** [comment]
Make sure you use:
http://pycollada.readthedocs.org/en/latest/

The public link is broken (I will cut a new release and update it):
http://pycollada.readthedocs.org/

You have to call the `save` method before the XML node is updated:
http://pycollada.readthedocs.org/en/latest/reference/generated/collada.Collada.html#collada.Collada.save

Or, I'd suggest instead to call the `write` method with a `StringIO` instance if you want to save the contents to a string:
http://pycollada.readthedocs.org/en/latest/reference/generated/collada.Collada.html#collada.Collada.write

**Comment by Tcll** [comment]
haha, alright :)

I think I'll use save()
if it's just like my UI.update() (repositions UI items and recompiles the display list), then handling it shouldn't be difficult :)

also, if you want to reference me in your used projects list, I don't have anything spectacular like a website, but I do have this:
http://tcll5850.proboards.com/thread/143/official-universal-converter-development-thread

I'll let you know if I ever upgrade though :)
I do have a forum I'm working on on my own server for use with UMC integration ;)
(your profile will actively display the scripts you've built and helped develop and what groups you're in)
