### ISSUE TITLE
bad (not horrible) examples

### ISSUE THREAD

**Issue by Tcll** [pycollada/pycollada#45]
I'm looking at your old-style renderer to figure out a bunch of stuff, and am having a problem trying to get facepoints from the primitives...

https://github.com/pycollada/pycollada/blob/master/examples/daeview/renderer/OldStyleRenderer.py
it seems this can only do triangles

the new-style renderer is a bad example as it generates normals...
really guys... 9_9
I can understand this when there are no normals, but you guys are skipping that check.

I mean, my renderer for my program may suck, but at least I display everything as is rather than recalculate it.
(my renderer stores the model in a display list to achieve a high framerate)

if you guys are like me though and are not exactly "pro", then yea, I can make an exception.
if this is the case, feel free to reference my src and apply it yo yours. ;)
https://copy.com/tadw3FFFJzimqEDb
NOTE: designed for python 2.7 (not following pythonic standards for performance)

sorry for the obfuscated names, I knew alot less when I built this thing.
what you'll want to look at is __M() which generates the Model display list
__N() is for blender-style Vertex-Normals
__B() is for Bone display

don't criticize plox, I know it sucks, and can't wait to scrap it for my newer GLSL rebuild.

**Comment by Tcll** [comment]
WTF!
even this dude converts them to triangles:
https://github.com/skrat/bpycollada/blob/master/import_collada.py

line 122
same code found in your renderer >3<

LAME
I'd like to use the full set of UMC's primitives to reduce data-size issues in the taget model format please!

**Comment by jterrace** [comment]
daeview was a contribution from a user. You're welcome to submit your own pull request.

**Comment by Tcll** [comment]
ah, well alright then :)

I can't submit my own as I'm rather tied up, but yea, I understand how that goes ;)

and just to note, I'm not mad, and never was, so I hope you didn't take my above attitude as such.
(I know it looks like it, but that was just utter disappointment that it's taking me 2+ days to write my script)
