### ISSUE TITLE
request for less or portable dependencies

### ISSUE THREAD

**Issue by Tcll** [pycollada/pycollada#46]
I'm using a portable python interpreter and overlooked the dependencies when installing...
so of course I got:

    WARNING: Collada library failed to load.

    Traceback (most recent call last):
      File "Z:\home\tcll\sync\copy\UMC_v3.0a\data\COMMON.py", line 110, in ugeScriptLibs
        try: _UGE_Module.__dict__.update(__import__(lib).__dict__)
      File "libs\Collada.py", line 2, in <module>
        from collada import *
      File "libs\collada\__init__.py", line 31, in <module>
        from collada import asset
      File "libs\collada\asset.py", line 17, in <module>
        import dateutil.parser
    ImportError: No module named dateutil.parser

doesn't python have a built-in date handler??

I'm having fun implementing these 9_9
dateutil requires six
and lxml is a freakin binary >3< *annoyed*

this is why I hate dependencies >_<

**Comment by jterrace** [comment]
re:dateparse: no, the built-in Python date parsing routines are awful. dateutil is the defacto standard for Python

re: lxml: it is optional. If lxml is not available, it will fall back to the built-in Python XML library. But note that lxml is *much* faster.

**Comment by Tcll** [comment]
>re: lxml: it is optional. If lxml is not available, it will fall back to the built-in Python XML library. But note that lxml is much faster.

alright, that's cool :)

>re:dateparse: no, the built-in Python date parsing routines are awful. dateutil is the defacto standard for Python

I see...
well I've managed to get it to load by placing it in collada/dateutil/
that's how I found out about six :)
hopefully that'll be easy enough to implement.
