### ISSUE TITLE
pycollada license?

### ISSUE THREAD

**Issue by bdon** [pycollada/pycollada#51]
Hi,

Thank you for this library! I was wondering if it would be possible to include licensing terms in the repository to make it clear how this library can be used. 

I've referred to http://choosealicense.com before which is helpful.

Thanks,

Brandon

**Comment by jterrace** [comment]
https://github.com/pycollada/pycollada/blob/master/COPYING

**Comment by bdon** [comment]
I am blind :see_no_evil: thanks
