### ISSUE TITLE
Pycollada for Autodesk Fusion360.

### ISSUE THREAD

**Issue by Anton-Volkov** [pycollada/pycollada#52]
Good day!

Please, help me with this question.
Can I use pycollada to create addin for Autodesk Fusion 360?  Windows 7 Professional 64-bit, Python 3.3.5, numpy (1.9.2), pycollada (0.4.1).
I used pip module to install numpy and pycollada. In code I write "import collada" and then I get access to all functions and objects of pycollada using "pycollada.[object]". However, when I run code, import error rises:

> > > Traceback (most recent call last):
> > >   File "D:/Projects/2-ExportModel/2/CAD to Earth Fusion 360. Python/CAD to Earth Fusion 360.py", line 13, in <module>
> > >     import collada
> > >   File "C:\Users\Anton\AppData\Local\Autodesk\webdeploy\production\d823d7c932fe4a7e4d638cb6af4b3845addcfe7d\Python\lib\collada__init__.py", line 30, in <module>
> > >     from collada import animation
> > > ImportError: cannot import name animation

Am I right, it is due to mismatch of python version? Can I still get to work pycollada with Python 3.3.5 on Windows? Or is it impossible? I need only the functional of creating .dae files.

Best Regards,
Anton.

P.S. Sorry for my English.

**Comment by jterrace** [comment]
Is this the actual file being imported?

````
C:\Users\Anton\AppData\Local\Autodesk\webdeploy\production\d823d7c932fe4a7e4d638cb6af4b3845addcfe7d\Python\lib\collada__init__.py
````

Because I would expect `collada/__init__.py`, but there's a missing slash. How did the file wind up with that name?

**Comment by Anton-Volkov** [comment]
File "D:/Projects/2-ExportModel/with pycollada/2/CAD to Earth Fusion 360. Python/CAD to Earth Fusion 360.py", line 14, in <module>
    import collada
  File "C:\Users\Anton\AppData\Local\Autodesk\webdeploy\production\d823d7c932fe4a7e4d638cb6af4b3845addcfe7d\Python\lib\collada\__init__.py", line 30, in <module>
    from collada import animation
ImportError: cannot import name animation

It is correct error message. (I don't know, why slash disappeared...)
The file  __init__.py does exist in directory C:\Users\Anton\AppData\Local\Autodesk\webdeploy\production\d823d7c932fe4a7e4d638cb6af4b3845addcfe7d\Python\lib\collada\ .
And when I check installed packages with command "pip list", it shows:
"numpy (1.9.2)
pip (7.1.0)
pycollada (0.4.1)
python-dateutil (2.4.2)
setuptools (18.1)
six (1.9.0)
wheel (0.24.0)"

Was pycollada tested with Python 3.3.5? The problem isn't associated with the Python's version?

**Comment by jterrace** [comment]
No, we test against 3.x. You can see the 3.3 run on Travis CI passing:
https://travis-ci.org/pycollada/pycollada

**Comment by Anton-Volkov** [comment]
Ok.
When I also test it in command prompt it looks like it works:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Anton>python
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from collada import *
>>> animation
<module 'collada.animation' from 'C:\\Users\\Anton\\AppData\\Local\\Autodesk\\we
bdeploy\\production\\d823d7c932fe4a7e4d638cb6af4b3845addcfe7d\\Python\\lib\\coll
ada\\animation.py'>
>>> Collada()
<Collada geometries=0>

But it doesn't find modules in Fusion 360.

**Comment by jterrace** [comment]
It sounds like something is wrong with the PYTHONPATH in Fusion. I have never used it before so I don't think I'll be much help.
