### ISSUE TITLE
Export to DAE via pycollada explodes memory/crashes freecad

### ISSUE THREAD

**Issue by hedgehog** [pycollada/pycollada#64]
Hi FreeCAD uses pycollada.  I reported FreeCAD crashing when exporting the given file to DAE format.
Another user reproduced the crash.  Another user reported "insane" memory usage.
The consensus was that this is an issue with pycollada.
The details are here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=21790&p=169839#p169517

The source of the meshes was an export from Sketchup.  I don't have access to the sketchup files just this.

Happy to help further if you need.

**Comment by jterrace** [comment]
Can you point to FreeCAD's code that does the export?

**Comment by toverux** [comment]
Same here, the export is slow and take a hudge amount of memory. I have some STEP files, and as soon as they get beyond a few megs, my 16 GiB of RAM are not enough anymore to handle the conversion.
The module that exports Collada files is `importDAE`.

**Comment by toverux** [comment]
The problem comes from there: https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Arch/importDAE.py#L217
When there are too much face indices, the array grows until the OOM.

**Comment by jterrace** [comment]
Those loops look incredibly inefficient. It'd be ideal if those three arrays could be created in bulk to numpy and then massaged as numpy arrays, instead of buildling python lists like that.

Even just switching from range to xrange would probably help - for a large mesh, that range is creating a huge list for no reason.

**Comment by jterrace** [comment]
I created https://github.com/FreeCAD/FreeCAD/pull/753 to start - this is really low hanging fruit.

I don't know what type m.Topology[1] is, but if it's a numpy array, findex could be created with numpy statements, which would speed up the creation by a couple orders of magnitude and use much less memory.

**Comment by jterrace** [comment]
That pull request has been submitted. Can someone try it out and see if it makes any difference?

**Comment by toverux** [comment]
Thanks a lot for you interest @jterrace!
I've already tried to replace range() by xrange() yesterday, following your comments and the PR. But the behaviour seems to stay the same: the conversion eats gigabytes one after the other.
