### ISSUE TITLE
instance_material only populating once per material type

### ISSUE THREAD

**Issue by steve-goley** [pycollada/pycollada#66]
# Description of Issue
I think I've found an issue in how the library_visual_scenes are written. I have built a complex geometry with materials in the library_scene section of the xml the instance_material tag under geometry nodes is not populating properly. It appears to only populate one per material target and I think it's the last geometry node that contains this instance_material. This is the last geometry node in the library scene:
`
 <node name="lastnode" id="lastnode">
 <instance_geometry url="#lastnode">
              <bind_material>
                <technique_common>
                  <instance_material symbol="metal" target="#100"/>
                </technique_common>
              </bind_material>
            </instance_geometry>
          </node>
`
It is also the only node with the "#100" target though many other nodes should have this instance_material.

The next to last geometry node looks like this:
`
            <node name="ftDrvShft" id="ftDrvShft">
              <instance_geometry url="#ftDrvShft">
                <bind_material>
                  <technique_common/>
                </bind_material>
              </instance_geometry>
            </node>
`
I've tried to do some debugging but haven't been able to get all the instance_materials to populate. Can someone verify that they can write out a DAE model with many geometry nodes with the same instance_material? 

# Basic Info
I'm using py27 and version 0.5 of pycollada.

# Use Case
I am converting a CAD model from a different format and I'm trying to import it into Blender. I'd like to get the materials to port over to Blender. 

Thanks!

**Comment by jterrace** [comment]
You should definitely be able to reference the same material multiple times in a GeometryNode.

I wrote a filter in meshtool a while ago that combines multiple identical materials together by referencing them in multiple geometry nodes. Maybe this code reference will help?
https://github.com/pycollada/meshtool/blob/master/meshtool/filters/optimize_filters/combine_materials.py

**Comment by steve-goley** [comment]
Thanks for the quick reply. I will check it out.  Here's the essential part of the code that I'm using to convert.

Note I've started with a very simple material effect but I will add more if I can get this to work. 

Do you see any glaring bugs?

`def create_py_collada(mmp):

    def create_geometry_node(component, mmp, material_node_dict):
        # get the vertex list
        first_facet = np.min(component.facet_ids)
        last_facet = np.max(component.facet_ids)

        first_vert = np.min(mmp.facets[first_facet:last_facet + 1, :])
        last_vert = np.max(mmp.facets[first_facet:last_facet + 1, :])
        this_comp_verts = mmp.vertices[first_vert:last_vert + 1, :].flatten()
        vert_src = source.FloatSource(component.name, this_comp_verts, ('X', 'Y', 'Z'))

        # create the geometry
        geom = geometry.Geometry(mesh, component.name, component.name, [vert_src])

        # create the indices
        indices = mmp.facets[component.facet_ids, :].flatten() - first_vert

        # create the input list for the vertices
        input_list = source.InputList()
        input_list.addInput(0, 'VERTEX', '#' + component.name)

        # create the triangle set for the indices
        triangle_set = geom.createTriangleSet(indices, input_list, str(component.material_id))

        # add these to the geometries and mesh
        geom.primitives.append(triangle_set)
        mesh.geometries.append(geom)

        # return the geometry
        # return scene.GeometryNode(geom, materials=[material_node_dict[component.material_id]])

        if material_node_dict.has_key(component.material_id):
            return scene.GeometryNode(geom, materials=[material_node_dict[component.material_id]])
        else:
            return scene.GeometryNode(geom, materials=[material_node_dict[1]])


    def get_child_node(mmp, child_component, material_node_dict):
        if child_component.children is not None:
            children_nodes = list()
            for child in child_component.children:
                children_nodes.append(get_child_node(mmp, child, material_node_dict))
        if child_component.facet_ids is not None:
            children_nodes.append(create_geometry_node(child_component, mmp, material_node_dict))
        return scene.Node(child_component.name, children_nodes)

    # create the mesh
    mesh = Collada()

    # let's add the material table

    # for now i'll just use one effect
    material_effect = material.Effect('effect0', [], 'phong', diffuse=(1, 0, 0), specular=(0, 1, 0))
    my_materials = list()
    material_nodes = dict()
    for material_id in mmp.material_table:
        this_material = material.Material(str(material_id), mmp.material_table[material_id], material_effect)
        my_materials.append(this_material)
        mesh.materials.append(this_material)
        material_nodes[material_id] = scene.MaterialNode(mmp.material_table[material_id], this_material, inputs=[])

    all_nodes = list()
    for child in mmp.components.children:
        if child.name == "GroundPlane": # this should be an input flag
            continue
        children_nodes = get_child_node(mmp, child, material_nodes)
        if mmp.components.facet_ids is not None:
            children_nodes.append(create_geometry_node(mmp.components, mmp, material_nodes))
        all_nodes.append(children_nodes)
    my_scene = scene.Scene("my_scene", all_nodes)
    mesh.effects.append(material_effect)
    mesh.scenes.append(my_scene)
    mesh.assetInfo.upaxis = 'Z_UP'
    return mesh`

**Comment by jterrace** [comment]
Do you know for sure that the material_id values in mmp.material_table are all unique?

Otherwise, I don't immediately see any glaring bugs, but there's a lot of code to follow and I don't know the data structure in mmp.

**Comment by steve-goley** [comment]
Yes they are.

I through in the `for` loop that you had starting at line 25 and replaced the line 36 with `print(node.geometry.id + " " + matnode.symbol)` and it printed every geometry node with the symbol of the material (the value in the mmp.material_table).

**Comment by steve-goley** [comment]
@jterrace I figured it out. A new `MaterialNode` has to be created for each `GeometryNode`, or a deepcopy. I think the material_node kept getting it's xmlnode passed to a new parent, I created a game of hot potato for the `MaterialNode`.

Thanks for you help!
