### ISSUE TITLE
readthedocs is still at 0.4

### ISSUE THREAD

**Issue by simonschmeisser** [pycollada/pycollada#67]
as stated in the title, http://pycollada.readthedocs.org is still at 0.4 (not sure if anything actually changed wrt external interfaces but it just looks outdated)

ie I'm redirected to http://pycollada.readthedocs.io/en/v0.4/ but would expect http://pycollada.readthedocs.io/en/v0.5/ (which doesn't exist yet)

**Comment by jterrace** [comment]
Should be fixed now.

**Comment by simonschmeisser** [comment]
Nice, the url now says 0.6 and i can chose 0.5 and 0.6 from menu etc but the header still says 0.4 and the changelog stopped at 0.4

**Comment by jterrace** [comment]
Okay, I think it's fixed for real now.
