### ISSUE TITLE
Use of xrange breaks python 3 support

### ISSUE THREAD

**Issue by lejar** [pycollada/pycollada#74]
```
~\Desktop\virt\lib\site-packages\collada\lineset.py in lines(self)
    242         :rtype: generator of :class:`collada.lineset.Line`
    243         """
--> 244         for i in xrange(self.nlines): yield self[i]
    245
    246     def shapes(self):

NameError: name 'xrange' is not defined
```

**Comment by lejar** [comment]
I can fix this, but would it be preferred to:
1. Simply use range and forego an iterator in python 2
2. Try except NameError and use range in except?
3. Use six?

**Comment by jterrace** [comment]
Looks like we're missing tests for lineset as well.

In util.py, we have an xrange defined based on the python version, so the simple fix is to change xrange to util.xrange. If you plan to send me a pull request, I'd love to see a new test added for lineset as well if you have the time. Thanks!
