### ISSUE TITLE
PyPi release

### ISSUE THREAD

**Issue by mikedh** [pycollada/pycollada#89]
It looks like the latest [release on PyPi](https://pypi.org/project/pycollada/#files) was a while ago, any plans for a new release?

**Comment by jterrace** [comment]
Yeah, probably time given the python 3.x compatibility changes especially. Will try to get to it this week.

**Comment by darkdragon-001** [comment]
Any updates?

**Comment by qwertychouskie** [comment]
@jterrace it's been a while and a new version still hasn't been uploaded, any updates on when this might happen?

**Comment by jterrace** [comment]
This should be all set, I built and pushed 0.7. Sorry for the delay!

**Comment by qwertychouskie** [comment]
Looks good, thanks!
