### ISSUE TITLE
pycollada is not compatible with Python 3.9

### ISSUE THREAD

**Issue by hobbes1069** [pycollada/pycollada#95]
See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"Methods getchildren() and getiterator() in the ElementTree module have been removed. They were deprecated in Python 3.2. Use functions list() and iter() instead. The xml.etree.cElementTree module has been removed."

Fedora bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1792032

**Comment by jterrace** [comment]
Isn't 3.9 still in alpha? We will likely not support it until it's actually released. That being said, if someone wants to submit a patch that fixes support, I'm fine with that as long as it doesn't break our supported versions.

**Comment by hobbes1069** [comment]
Well as the Fedora bugzilla notes, this is "in preparation" for Python 3.9 which will be in Fedora 33 so there is some time, but my guess is these methods have been deprecated for some time and their substitutions should work find in any 3.X version of Python.

**Comment by jterrace** [comment]
Sorry for the really long delay. 0.7.2 just released.
