### ISSUE TITLE
Wrong code comments about angle unit

### ISSUE THREAD

**Issue by lichenbo** [pycollada/pycollada#96]
Angle of rotation passed in when building rotation matrix should be in degrees instead of radians.

Code comments I can find for now:

https://github.com/pycollada/pycollada/blob/06284d3cec1ca8e9b675fd6292ef990d872cc581/collada/scene.py#L139

and 

https://github.com/pycollada/pycollada/blob/06284d3cec1ca8e9b675fd6292ef990d872cc581/collada/scene.py#L151

**Comment by jterrace** [comment]
It looks like radians to me? The code is calling `numpy.cos` and `numpy.sin`, which take radians as input:
https://github.com/pycollada/pycollada/blob/06284d3cec1ca8e9b675fd6292ef990d872cc581/collada/scene.py#L65

**Comment by lichenbo** [comment]
It has been converted here from degrees to radians. But the places I am referring to before are actually expecting degrees.

https://github.com/pycollada/pycollada/blob/06284d3cec1ca8e9b675fd6292ef990d872cc581/collada/scene.py#L152

**Comment by jterrace** [comment]
Ah, sorry, I missed that.
